import type {Mode,Prompt} from './types';
export const modes:Mode[]=['General Prompt','Location Prompt','Story Starter','Opening Frame','Character','Context','Relationship','Detail','Action','Tension','Change','Sound Into Image','Before and After','Portrait','Sequence','Closing Frame','Reflection','Constraint Challenge'];
const subjects=['a routine most visitors overlook','a person whose work shapes the place','an object that passes between people','a boundary people cross or negotiate','evidence of someone who is absent','a place where people pause','an exchange between two people','a repeated gesture'];
const actions=['preparing','waiting','repairing','teaching','carrying','arriving','listening','sorting','leaving','sharing'];
const approaches=['build a three-frame sequence','work from one position for ten minutes','follow the changing light','photograph without directing the action','pair a wide frame with a close detail','use foreground and background together','observe before raising the camera'];
const purposes=['reveal how the place functions','introduce a possible character','show a relationship that is easy to miss','connect a private action to its public context','suggest what happened before this moment','leave room for uncertainty'];
const details=['worn tools','hands at work','traces on a surface','personal objects','signs of repair','light at an entrance','what remains after activity'];
const contrasts=['stillness and movement','public and private space','preparation and completion','individual and group activity','what is permanent and temporary','expectation and reality'];
const reflections=['What might a viewer misunderstand from one frame?','Whose perspective is missing?','What changed after you stayed longer?','Does the frame preserve the subject’s dignity?','What lies just outside the frame?'];
const ethics=['Ask for consent when appropriate and give people room to decline.','Do not ask anyone to repeat a sensitive action.','Avoid revealing private information or a vulnerable person’s location.','Distinguish observation from staging.'];
const titles=['A Rhythm Beneath the Surface','The Space Between Moments','What the Place Holds','A Trace of Daily Life','Where Paths Cross','Before the Next Arrival'];
function hash(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function pick<T>(a:T[],seed:number,offset:number){return a[(seed+offset*2654435761>>>0)%a.length]}
export function sanitize(value:string){return value.replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,120)}
export function generatePrompt(input:{seed:string;spin:number;mode:Mode;location?:string;placeType?:string;recent?:Prompt[]}):Prompt{
 const random=new Uint32Array(1);crypto.getRandomValues(random); let attempt=0; let prompt:Prompt;
 do { const n=hash(`${input.seed}|${input.spin}|${input.mode}|${input.location}|${random[0]}|${attempt++}`); const components=[pick(subjects,n,1),pick(actions,n,2),pick(approaches,n,3),pick(purposes,n,4),pick(details,n,5),pick(contrasts,n,6)]; const loc=sanitize(input.location||''); const lead=loc&&input.mode!=='General Prompt'?`At ${loc}, `:''; const fp=components.join('|'); prompt={id:crypto.randomUUID(),fingerprint:fp,mode:input.mode,title:pick(titles,n,7),assignment:`${lead}find ${components[0]}. Photograph the moment of ${components[1]}, then ${components[2]}. Include ${components[4]} and look for the contrast between ${components[5]}.`,why:`This can ${components[3]} without assuming what the place or its people are like.`,variation:`Try one wide image, one medium frame, and one close observation using available light.`,reflection:pick(reflections,n,8),role:input.mode==='General Prompt'?'Observation and context':input.mode,difficulty:pick(['Gentle','Focused','Challenging'],n,9),time:pick(['10–15 min','20–30 min','45–60 min'],n,10),ethics:pick(ethics,n,11),components,createdAt:new Date().toISOString()};
 } while(input.recent?.some(p=>p.fingerprint===prompt.fingerprint)&&attempt<50); return prompt;
}
